spring.application.name=SoapFul

server.servlet.context-path=/restapi/v1
server.port=443

# Enable SpringDoc /v3/api-docs endpoint
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.use-management-port=false
springdoc.swagger-ui.path=/swagger-ui.html

cxf.jaxrs.component-scan=true

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=changeit
# Uncomment if you do not want to use HTTPS
# server.ssl.enabled=false

# Enable HTTP/2 because why not
server.http2.enabled=true

management.server.port=80
management.server.ssl.enabled=false
